= Demo project for shaded elasticsearch and shield

This project shows how to create an embedded version of shield and elasticsearch
with package relocation to avoid some conflicts with your existing project libs.


== Install the demo

First download elasticsearch 2.0.0-beta1, install it, install shield and license plugins.

[source,shell]
----------------
wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.0.0-beta1/elasticsearch-2.0.0-beta1.tar.gz
tar xzv elasticsearch-2.0.0-beta1.tar.gz
cd elasticsearch-2.0.0-beta1
bin/plugin install license
bin/plugin install shield
bin/shield/esusers useradd dadoonet -p azerty -r admin
bin/elasticsearch
----------------

Check that everything is fine:

[source,shell]
----------------
# should fail
curl localhost:9200
# should work
curl localhost:9200?pretty -u dadoonet:azerty
----------------

== Fork this project

This project has 3 modules:

* parent project `shaded-test`
* `es-shaded`: the goal is to shade here whatever library you want and relocate potentially any library
which conflicts with your own project. For example, here we shaded JODA 2.8
* `es-test`: the final project you want to build. This one depends on `es-shaded` and on the libraries you need for
your project. For example, here we added JODA 2.1.

Run:

[source,shell]
-------------------
mvn clean install
-------------------

You should see:

[source,shell]
-------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
-------------------------------------------------------

It means that test were executed correctly.

Tests are basically:

* `testJodaLibVersion()`

[source,java]
-------------------------------------------------------
CodeSource codeSource = new org.joda.time.DateTime().getClass().getProtectionDomain().getCodeSource();
assertThat(codeSource.getLocation().getFile(), containsString("joda-time-2.1.jar"));

codeSource = new fr.pilato.thirdparty.joda.time.DateTime().getClass().getProtectionDomain().getCodeSource();
assertThat(codeSource.getLocation().getFile(), containsString("es-shaded-1.0-SNAPSHOT.jar"));
-------------------------------------------------------

* `testShadedClient()`

[source,java]
-------------------------------------------------------
TransportClient client = TransportClient.builder()
        .settings(Settings.builder()
                        .put("path.home", ".")
                        .put("shield.user", "dadoonet:azerty")
                        .put("plugin.types", "org.elasticsearch.shield.ShieldPlugin")

        )
        .build();
client.addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress("localhost", 9300)));
ClusterHealthResponse health = client.admin().cluster().prepareHealth().setWaitForYellowStatus().get();
assertThat(health.getClusterName(), is("elasticsearch"));

try {
    client.admin().indices().prepareDelete("test").get();
} catch (IndexNotFoundException e) {
    // That's fine
}

client.prepareIndex("test", "doc", "1").setSource("foo", "bar").setRefresh(true).get();
SearchResponse searchResponse = client.prepareSearch("test").get();
assertThat(searchResponse.getHits().getTotalHits(), is(1L));
-------------------------------------------------------
